language: python
python:
  - 2.7
install:
  - pip install -r requirements/development.txt
script:
  - export PYTHONPATH=.
  - flake8 --ignore=W801,E128,E501,W402 cab ratings comments_spamfighter
  - python manage.py test --settings=cab.tests.settings
